name: Deploy develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  aws_deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout street-view-manager
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.19.1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
    - name: Install yarn
      shell: pwsh
      run: npm install -g yarn
    - name: Install client packages
      shell: pwsh
      run: |
        Push-Location ./client
        ./Invoke-InstallClientPackages.ps1
        Pop-Location
    - name: Run client unit tests
      shell: pwsh
      run: |
        Push-Location ./client
        ./Invoke-RunUnitTests.ps1
        Pop-Location
    #- name: Install cypress
    #  uses: cypress-io/github-action@v6
    #  with:
    #    runTests: false
    - name: Run client e2e tests
      uses: cypress-io/github-action@v6
      with:
        project: ./client
    - name: Build deployable client files
      shell: pwsh
      run: |
        Push-Location ./server
        ./Invoke-BuildClient.ps1
        Pop-Location
    - name: Install server packages
      shell: pwsh
      run: |
        Push-Location ./server
        ./Invoke-InstallServerPackages.ps1
        Pop-Location
    - name: Upload to AWS lambda function
      shell: pwsh
      run: |
        Push-Location ./server

        ./Invoke-UploadStreetViewManager.ps1 `
          -AppClientId '${{ vars.DEV_APP_CLIENT_ID }}' `
          -AppKey '${{ vars.DEV_APP_KEY }}' `
          -LambdaFunctionName '${{ vars.DEV_LAMBDA_FUNCTION_NAME }}' `
          -CloudFrontDistributionID '${{ vars.DEV_CLOUDFRONT_DISTRIBUTION_ID }}'

        Pop-Location
